[workspace]
resolver = "3"
members = [
    "dst-factory",
    "examples",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
categories = ["memory-management", "no-std"]
description = "Macros to implement C's flexible array members in Rust"
keywords = ["memory", "no_std", "ffi"]
repository = "https://github.com/geeknoid/dst-factory"
license = "MIT"
authors = ["Martin Taillefer <martin@taillefer.org>"]
readme = "README.md"
rust-version = "1.85.0"

[workspace.dependencies]
dst-factory = { path = "dst-factory" }
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full", "visit", "extra-traits", "clone-impls"], default-features = false }
proc-macro2 = "1.0.95"
trybuild = "1.0.105"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }

[profile.bench]
codegen-units = 1
lto = "fat"

[profile.release]
codegen-units = 1
lto = "fat"
debug = true
strip = "none"
